Repository AY2021S2-CS2113-T10-1/tp, pull requests merged in 2021-03, with the labels that each got.

#43 Implement LocalDate
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidDateException.java
  src/main/java/seedu/fridgefriend/food/ExpiryDate.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/test/java/seedu/fridgefriend/FoodTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
Labels: priority.High, type.Task

#45 Add More OOP
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/ByeCommand.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/command/SearchCommand.java
  src/main/java/seedu/fridgefriend/exception/EmptyDescriptionException.java
  src/main/java/seedu/fridgefriend/exception/InvalidIndexException.java
  src/main/java/seedu/fridgefriend/exception/InvalidInputException.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#49 Add HelpCommand
  src/main/java/seedu/fridgefriend/command/HelpCommand.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement

#52 Add Logging for FridgeFriend
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/utilities/Logger.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
Labels: priority.Medium, type.Task

#54 JUnit test add command
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
Labels: type.Task

#56 Add JUnit-test RemoveCommandTest.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
Labels: type.Task

#60 Add ListCommandTest
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
Labels: type.Task

#62 Fix major bug
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/command/SearchCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidIndexException.java
  src/main/java/seedu/fridgefriend/food/ExpiryDate.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug

#58 Add JUnit-SearchCommandTest
  src/main/java/seedu/fridgefriend/command/SearchCommand.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
  src/test/java/seedu/fridgefriend/command/SearchCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#47 Add ParseTest
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/test/java/seedu/fridgefriend/food/FoodTest.java
  src/test/java/seedu/fridgefriend/utilities/ParserTest.java
Labels: priority.Medium, type.Enhancement

#64 Add loggers, asserts and modify FoodTest
  src/main/java/seedu/fridgefriend/food/ExpiryDate.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/test/java/seedu/fridgefriend/food/FoodTest.java
Labels: priority.Medium, type.Enhancement

#66 Add Expiring Command
  save/savefile.txt
  src/main/java/seedu/fridgefriend/command/ExpiringCommand.java
  src/main/java/seedu/fridgefriend/command/HelpCommand.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#65 Added Assertions and Logging, fixed very minor formatting bug
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/command/SearchCommand.java
  src/main/java/seedu/fridgefriend/food/Food.java
Labels: priority.Medium, type.Enhancement

#68 Improved coding standards for Storage class
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/exception/NoSaveException.java
  src/main/java/seedu/fridgefriend/exception/StorageLoadingException.java
  src/main/java/seedu/fridgefriend/exception/StorageSavingException.java
  src/main/java/seedu/fridgefriend/utilities/Save.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
Labels: priority.High, severity.Low, type.Task

#67 Update UserGuide on list and FAQ
  docs/UserGuide.md
  docs/team/wenqihu.md
Labels: priority.Medium, type.Task

#69 Added expiring feature in user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#48 Updated AboutUs
  docs/AboutUs.md
  docs/team/jw_pic.png
  docs/team/kwokyto.md
  docs/team/kwokyto_pic.jpg
  docs/team/lyp_pic.png
  docs/team/sjj_pic.png
Labels: type.Task

#76 Add FridgeFriend.jar
  FridgeFriend.jar
  docs/UserGuide.md
  src/main/java/seedu/fridgefriend/FridgeFriend.java
Labels: priority.High, type.Task

#79 Fix bug in listCommand.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
Labels: severity.VeryLow, type.Bug

#91 Set up puml
  docs/diagrams/style.puml
Labels: priority.High, type.Task

#93 Add Food Classes for each Category, also, List all Food by Storage Location
  docs/UserGuide.md
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/main/java/seedu/fridgefriend/food/categories/Beverage.java
  src/main/java/seedu/fridgefriend/food/categories/CookedDish.java
  src/main/java/seedu/fridgefriend/food/categories/Dairy.java
  src/main/java/seedu/fridgefriend/food/categories/Egg.java
  src/main/java/seedu/fridgefriend/food/categories/Frozen.java
  src/main/java/seedu/fridgefriend/food/categories/Fruit.java
  src/main/java/seedu/fridgefriend/food/categories/Meat.java
  src/main/java/seedu/fridgefriend/food/categories/Other.java
  src/main/java/seedu/fridgefriend/food/categories/ReadyToEat.java
  src/main/java/seedu/fridgefriend/food/categories/Seafood.java
  src/main/java/seedu/fridgefriend/food/categories/Vegetable.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
  src/test/java/seedu/fridgefriend/command/SearchCommandTest.java
  src/test/java/seedu/fridgefriend/food/FoodTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story, type.Task

#108 Add quantity
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/ExpiringCommand.java
  src/main/java/seedu/fridgefriend/command/HelpCommand.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidQuantityException.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/food/categories/Beverage.java
  src/main/java/seedu/fridgefriend/food/categories/CookedDish.java
  src/main/java/seedu/fridgefriend/food/categories/Dairy.java
  src/main/java/seedu/fridgefriend/food/categories/Egg.java
  src/main/java/seedu/fridgefriend/food/categories/Frozen.java
  src/main/java/seedu/fridgefriend/food/categories/Fruit.java
  src/main/java/seedu/fridgefriend/food/categories/Meat.java
  src/main/java/seedu/fridgefriend/food/categories/Other.java
  src/main/java/seedu/fridgefriend/food/categories/ReadyToEat.java
  src/main/java/seedu/fridgefriend/food/categories/Seafood.java
  src/main/java/seedu/fridgefriend/food/categories/Vegetable.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
  src/test/java/seedu/fridgefriend/command/SearchCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story, type.Task

#110 Refine Add and List commands to new quantity feature
  .gitignore
  data/data.txt
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/ClearCommand.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/exception/RepetitiveFoodIdentifierException.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/food/UniqueFoodnameChecker.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/data.txt
  text-ui-test/input.txt
Labels: priority.High, type.Task

#95 Modified expiring command
  src/main/java/seedu/fridgefriend/command/ExpiringCommand.java
  src/main/java/seedu/fridgefriend/food/Food.java
Labels: priority.Medium, type.Enhancement

#112 Running Low Warning
  data/data.txt
  src/main/java/seedu/fridgefriend/command/ClearCommand.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/main/java/seedu/fridgefriend/food/FoodCategory.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
  src/test/java/seedu/fridgefriend/utilities/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#117 Developers guide: Command Implementation
  docs/DeveloperGuide.md
  docs/diagrams/CommandClass.png
  docs/diagrams/command.puml
  docs/diagrams/style.puml
  src/main/java/seedu/fridgefriend/command/SetLimitCommand.java
Labels: priority.High, type.Task

#106 Developers Guide: Utilities Implementation
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UtilitiesClassDiagram.puml
  docs/diagrams/diagram_images/UtilitiesClassDiagram.png
  docs/diagrams/style.puml
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/main/java/seedu/fridgefriend/utilities/Ui.java
Labels: priority.High, type.Task

#107 Update kwokyto.md
  data/limits.txt
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/JoohwanPic.png
  docs/team/kwokyto.md
  docs/team/profile_pictures/hwq_pic.png
  docs/team/profile_pictures/jw_pic.png
  docs/team/profile_pictures/kwokyto_pic.jpg
  docs/team/profile_pictures/lyp_pic.png
  docs/team/profile_pictures/sjj_pic.png
Labels: priority.High, type.Task

#119 Added Exception for DG
  docs/DeveloperGuide.md
  docs/diagrams/ExceptionClassDiagram.puml
  docs/diagrams/UtilitiesClassDiagram.puml
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  src/main/java/seedu/fridgefriend/exception/FoodNameNotFoundException.java
  src/main/java/seedu/fridgefriend/exception/InvalidIndexException.java
  src/main/java/seedu/fridgefriend/exception/RepetitiveFoodIdentifierException.java
  src/main/java/seedu/fridgefriend/exception/StorageLoadingException.java
  src/main/java/seedu/fridgefriend/exception/StorageSavingException.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#94 Developer Guide: overall architecture diagram (very very high level)
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/diagram_images/ArchitectureDiagram.png
Labels: priority.High, type.Task

#121 Cosmetic change in Exception DG
  docs/diagrams/ExceptionClassDiagram.puml
Labels: severity.VeryLow, type.Task

#122 Cosmetic Change
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
Labels: severity.VeryLow, type.Task

#116 Developers Guide: Food Class Diagram and personal md update
  docs/diagrams/foodPackage.puml
  docs/diagrams/foodPackageClassDiagram.png
  docs/diagrams/style.puml
  docs/team/wenqihu.md
Labels: priority.High, type.Task

#127 Add @@author tags
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/command/SearchCommand.java
  src/main/java/seedu/fridgefriend/food/categories/Beverage.java
  src/main/java/seedu/fridgefriend/food/categories/CookedDish.java
  src/main/java/seedu/fridgefriend/food/categories/Dairy.java
  src/main/java/seedu/fridgefriend/food/categories/Egg.java
  src/main/java/seedu/fridgefriend/food/categories/Frozen.java
  src/main/java/seedu/fridgefriend/food/categories/Fruit.java
  src/main/java/seedu/fridgefriend/food/categories/Meat.java
  src/main/java/seedu/fridgefriend/food/categories/Other.java
  src/main/java/seedu/fridgefriend/food/categories/ReadyToEat.java
  src/main/java/seedu/fridgefriend/food/categories/Seafood.java
  src/main/java/seedu/fridgefriend/food/categories/Vegetable.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
Labels: type.Task

#130 Update UG (Content, List, Command Summary)
  docs/UserGuide.md
Labels: priority.High, type.Task

#132 Added Table of Contents
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#129 Added "Design and Implementation"
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#128 Edit Exception Component in DG
  docs/DeveloperGuide.md
  docs/diagrams/ExceptionClassDiagram.puml
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
Labels: priority.Medium, type.Task

#137 Modified Colours in style.puml
  docs/diagrams/style.puml
Labels: priority.High, type.Task

#138 Update style.puml
  docs/diagrams/style.puml
Labels: priority.High, type.Bug, type.Task

#133 Fix bug for AddCommand and Update SearchCommand
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/SearchCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidQuantityException.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/SearchCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: severity.High, type.Bug

#140 Edit DG NF requirements and UG add and remove
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/fridgefriend/command/ClearCommand.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/exception/FoodNameNotFoundException.java
  src/main/java/seedu/fridgefriend/exception/InvalidInputException.java
  src/main/java/seedu/fridgefriend/exception/InvalidQuantityException.java
  src/main/java/seedu/fridgefriend/exception/RepetitiveFoodIdentifierException.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/main/java/seedu/fridgefriend/food/FoodCategory.java
  src/main/java/seedu/fridgefriend/food/FoodStorageLocation.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/food/UniqueFoodnameChecker.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
  src/test/java/seedu/fridgefriend/utilities/ParserTest.java
Labels: priority.High, type.Task

#123 Update User Guide add and list features
  docs/UserGuide.md
Labels: priority.High, type.Task

#131 Added History Command
  docs/UserGuide.md
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/ClearCommand.java
  src/main/java/seedu/fridgefriend/command/HistoryCommand.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/test/java/seedu/fridgefriend/command/HistoryCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#143 Corrected Retroactive Merge Conflict
  src/test/java/seedu/fridgefriend/command/HistoryCommandTest.java
Labels: priority.High, severity.High, type.Bug

#134 Update Documentation
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/MainLogicSequenceDiagram.puml
  docs/diagrams/diagram_images/MainLogicSequenceDiagram.png
  docs/diagrams/diagram_images/foodPackageClassDiagram.png
  docs/diagrams/style.puml
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/command/ByeCommand.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/command/ExpiringCommand.java
  src/main/java/seedu/fridgefriend/command/HelpCommand.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/command/RunningLowCommand.java
  src/main/java/seedu/fridgefriend/command/SetLimitCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidDateException.java
  src/main/java/seedu/fridgefriend/exception/InvalidFoodCategoryException.java
  src/main/java/seedu/fridgefriend/exception/InvalidIndexException.java
  src/main/java/seedu/fridgefriend/exception/StorageLoadingException.java
  src/main/java/seedu/fridgefriend/exception/StorageSavingException.java
  src/main/java/seedu/fridgefriend/food/ExpiryDate.java
  src/main/java/seedu/fridgefriend/food/FoodCategory.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/utilities/LoggingHandler.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/main/java/seedu/fridgefriend/utilities/Ui.java
  src/test/java/seedu/fridgefriend/utilities/ParserTest.java
Labels: priority.High, type.Task

#135 Update kwokyto.md
  docs/team/kwokyto.md
Labels: priority.High, type.Task

#142 Add instructions for Manual Testing to the Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#141 Update Developers guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/ExpiringSeqeunceDiagram.puml
  docs/diagrams/RemoveSequenceDiagram.puml
  docs/diagrams/RunningLowSequenceDiagram.puml
  docs/diagrams/SearchSequenceDiagram.puml
  docs/diagrams/SetLimitSequenceDiagram.puml
  docs/diagrams/diagram_images/CommandClass.png
  docs/diagrams/diagram_images/CommandClassDiagram.png
  docs/diagrams/diagram_images/ExpiringSeqeunceDiagram.png
  docs/diagrams/diagram_images/RemoveSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/SearchSequenceDiagram.png
  docs/diagrams/diagram_images/SetLimitSequenceDiagram.png
  docs/diagrams/style.puml
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/command/SearchCommand.java
  src/main/java/seedu/fridgefriend/exception/EmptyDescriptionException.java
  src/main/java/seedu/fridgefriend/exception/InvalidInputException.java
  src/main/java/seedu/fridgefriend/exception/InvalidQuantityException.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/main/java/seedu/fridgefriend/food/FoodCategory.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
  src/test/java/seedu/fridgefriend/command/RemoveCommandTest.java
  src/test/java/seedu/fridgefriend/command/SearchCommandTest.java
  text-ui-test/ACTUAL.TXT
Labels: priority.High, type.Task

#147 AddCommand sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/diagram_images/AddSequenceDiagram.png
Labels: priority.High, type.Task

#148 (DG) List sequence diagram and Implementation
  docs/DeveloperGuide.md
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/diagram_images/ListCommandSequenceDiagram.png
Labels: priority.High, type.Task

#149 DG Cosmetic Changes
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/ExceptionClassDiagram.puml
  docs/diagrams/MainLogicSequenceDiagram.puml
  docs/diagrams/UtilitiesClassDiagram.puml
  docs/diagrams/diagram_images/AddSequenceDiagram.png
  docs/diagrams/diagram_images/ArchitectureDiagram.png
  docs/diagrams/diagram_images/CommandClassDiagram.png
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  docs/diagrams/diagram_images/ExpiringSeqeunceDiagram.png
  docs/diagrams/diagram_images/ListCommandSequenceDiagram.png
  docs/diagrams/diagram_images/MainLogicSequenceDiagram.png
  docs/diagrams/diagram_images/RemoveSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/SetLimitSequenceDiagram.png
  docs/diagrams/diagram_images/UtilitiesClassDiagram.png
  docs/diagrams/style.puml
  docs/team/kwokyto.md
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/exception/InvalidIndexException.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
Labels: severity.VeryLow, type.Task

#152 Update Developers guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/diagrams/ExpiringSeqeunceDiagram.puml
  docs/diagrams/RemoveSequenceDiagram.puml
  docs/diagrams/RunningLowSequenceDiagram.puml
  docs/diagrams/SearchSequenceDiagram.puml
  docs/diagrams/diagram_images/ExpiringSeqeunceDiagram.png
  docs/diagrams/diagram_images/RemoveSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/SearchSequenceDiagram.png
Labels: type.Task
