Repository AY2021S2-CS2113-T10-1/tp, pull requests merged in 2021-04, with the labels that each got.

#210 Remove expired limitation and fix display
  src/main/java/seedu/fridgefriend/command/ExpiringCommand.java
  src/main/java/seedu/fridgefriend/food/Food.java
  src/test/java/seedu/fridgefriend/command/ExpiringCommandTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
Labels: severity.High, type.Bug

#202 Bugfix quantity
  src/main/java/seedu/fridgefriend/command/AddCommand.java
  src/main/java/seedu/fridgefriend/command/RemoveCommand.java
  src/main/java/seedu/fridgefriend/command/RunningLowCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidQuantityException.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/RunningLowCommandTest.java
  src/test/java/seedu/fridgefriend/utilities/ParserTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.High, type.Bug

#208 Fixed Storage improper validation
  src/main/java/seedu/fridgefriend/utilities/Storage.java
Labels: priority.High, severity.Medium

#207 Allow only “others” input to go into others food category
  docs/DeveloperGuide.md
  docs/diagrams/ExceptionClassDiagram.puml
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/command/Command.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidFoodLocationException.java
  src/main/java/seedu/fridgefriend/food/FoodCategory.java
  src/main/java/seedu/fridgefriend/food/FoodStorageLocation.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, severity.Low

#212 Fixed Collision between list by category "others" and list by storage "others"
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/test/java/seedu/fridgefriend/command/ListCommandTest.java
Labels: priority.Medium, severity.Low

#204 UG Bug Fix
  data/data.txt
  data/limits.txt
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/ExceptionClassDiagram.puml
  docs/diagrams/ExpiringSeqeunceDiagram.puml
  docs/diagrams/FoodClassDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/RemoveSequenceDiagram.puml
  docs/diagrams/RunningLowSequenceDiagram.puml
  docs/diagrams/SearchSequenceDiagram.puml
  docs/diagrams/SetLimitSequenceDiagram.puml
  docs/diagrams/UtilitiesClassDiagram.puml
  docs/diagrams/diagram_images/CommandClassDiagram.png
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  docs/diagrams/diagram_images/FoodClassDiagram.png
  docs/diagrams/diagram_images/ListCommandSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/SetLimitSequenceDiagram.png
  docs/diagrams/diagram_images/UtilitiesClassDiagram.png
  docs/team/kwokyto.md
  src/main/java/seedu/fridgefriend/command/HelpCommand.java
  src/main/java/seedu/fridgefriend/command/RunningLowCommand.java
  src/main/java/seedu/fridgefriend/command/SetLimitCommand.java
  src/main/java/seedu/fridgefriend/food/FoodCategory.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/food/MinimumQuantity.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/test/java/seedu/fridgefriend/command/AddCommandTest.java
  src/test/java/seedu/fridgefriend/command/RunningLowCommandTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug, type.Task

#206 Update leeyp.md
  docs/team/leeyp.md
Labels: priority.High, type.Task

#213 Bugfix Miscellaneous and Update JavaDoc
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/ExceptionClassDiagram.puml
  docs/diagrams/ExpiringSeqeunceDiagram.puml
  docs/diagrams/RemoveSequenceDiagram.puml
  docs/diagrams/RunningLowSequenceDiagram.puml
  docs/diagrams/UtilitiesClassDiagram.puml
  docs/diagrams/diagram_images/CommandClassDiagram.png
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  docs/diagrams/diagram_images/ExpiringSeqeunceDiagram.png
  docs/diagrams/diagram_images/ExpiringSequenceDiagram.png
  docs/diagrams/diagram_images/RemoveSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/UtilitiesClassDiagram.png
  src/main/java/seedu/fridgefriend/command/ExpiringCommand.java
  src/main/java/seedu/fridgefriend/command/HelpCommand.java
  src/main/java/seedu/fridgefriend/command/HistoryCommand.java
  src/main/java/seedu/fridgefriend/command/ListCommand.java
  src/main/java/seedu/fridgefriend/command/RunningLowCommand.java
  src/main/java/seedu/fridgefriend/exception/InvalidInputException.java
  src/main/java/seedu/fridgefriend/exception/InvalidQuantityException.java
  src/main/java/seedu/fridgefriend/exception/InvalidSetLimitQuantityException.java
  src/main/java/seedu/fridgefriend/exception/RepetitiveFoodIdentifierException.java
  src/main/java/seedu/fridgefriend/food/Fridge.java
  src/main/java/seedu/fridgefriend/utilities/LoggingHandler.java
  src/main/java/seedu/fridgefriend/utilities/Parser.java
  src/main/java/seedu/fridgefriend/utilities/Storage.java
  src/main/java/seedu/fridgefriend/utilities/Ui.java
  src/test/java/seedu/fridgefriend/command/HistoryCommandTest.java
  src/test/java/seedu/fridgefriend/command/RunningLowCommandTest.java
  src/test/java/seedu/fridgefriend/utilities/ParserTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.Medium

#214 Bugfix
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.VeryLow, type.Bug

#203 Update kwokyto.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/team/kwokyto.md
Labels: priority.High, type.Task

#215 More Documentation Bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/FoodClassDiagram.puml
  docs/diagrams/MainLogicSequenceDiagram.puml
  docs/diagrams/SetLimitSequenceDiagram.puml
  docs/diagrams/diagram_images/AddSequenceDiagram.png
  docs/diagrams/diagram_images/ArchitectureDiagram.png
  docs/diagrams/diagram_images/CommandClassDiagram.png
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  docs/diagrams/diagram_images/ExpiringSequenceDiagram.png
  docs/diagrams/diagram_images/FoodClassDiagram.png
  docs/diagrams/diagram_images/MainLogicSequenceDiagram.png
  docs/diagrams/diagram_images/RemoveSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/SearchSequenceDiagram.png
  docs/diagrams/diagram_images/SetLimitSequenceDiagram.png
  docs/diagrams/diagram_images/UtilitiesClassDiagram.png
  docs/team/kwokyto.md
  src/main/java/seedu/fridgefriend/FridgeFriend.java
Labels: priority.High, severity.Medium, type.Bug

#216 Bugfix runtime exception
  src/main/java/seedu/fridgefriend/FridgeFriend.java
  src/main/java/seedu/fridgefriend/utilities/Ui.java
Labels: severity.Low, type.Bug

#209 Update simjingjie.md
  docs/team/simjingjie.md
Labels: priority.High, type.Task

#221 Personal md update
  data/fridgeData.txt
  data/historyData.txt
  data/limitsData.txt
  docs/team/wenqihu.md
  text-ui-test/data/fridgeData.txt
  text-ui-test/data/historyData.txt
  text-ui-test/data/limitsData.txt
Labels: type.Task

#223 Fixed saving data properly when app is interrupted
  data/fridgeData.txt
  data/historyData.txt
  data/limitsData.txt
  src/main/java/seedu/fridgefriend/FridgeFriend.java
Labels: severity.High, type.Bug

#224 Fixed Documentation Bugs
  docs/DeveloperGuide.md
  docs/team/kwokyto.md
Labels: priority.High, severity.Medium, type.Bug

#225 Documentation Bug Fix
  docs/DeveloperGuide.md
  docs/diagrams/diagram_images/AddSequenceDiagram.png
  docs/diagrams/diagram_images/CommandClassDiagram.png
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  docs/diagrams/diagram_images/ExpiringSequenceDiagram.png
  docs/diagrams/diagram_images/FoodClassDiagram.png
  docs/diagrams/diagram_images/ListCommandSequenceDiagram.png
  docs/diagrams/diagram_images/MainLogicSequenceDiagram.png
  docs/diagrams/diagram_images/RemoveSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/SearchSequenceDiagram.png
  docs/diagrams/diagram_images/SetLimitSequenceDiagram.png
  docs/diagrams/diagram_images/UtilitiesClassDiagram.png
Labels: priority.High, severity.Medium, type.Bug

#226 DG Bugs
  docs/UserGuide.md
  docs/diagrams/diagram_images/AddSequenceDiagram.png
  docs/diagrams/diagram_images/CommandClassDiagram.png
  docs/diagrams/diagram_images/ExceptionClassDiagram.png
  docs/diagrams/diagram_images/ExpiringSequenceDiagram.png
  docs/diagrams/diagram_images/FoodClassDiagram.png
  docs/diagrams/diagram_images/ListCommandSequenceDiagram.png
  docs/diagrams/diagram_images/MainLogicSequenceDiagram.png
  docs/diagrams/diagram_images/RemoveSequenceDiagram.png
  docs/diagrams/diagram_images/RunningLowSequenceDiagram.png
  docs/diagrams/diagram_images/SearchSequenceDiagram.png
  docs/diagrams/diagram_images/SetLimitSequenceDiagram.png
  docs/diagrams/diagram_images/UtilitiesClassDiagram.png
Labels: priority.High, severity.Medium, type.Bug

#227 More Documentation Bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.Medium, type.Bug

#228 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium, type.Bug
